insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('СУБД', 'Системы управления базами данных', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('БД', 'Базы данных', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ИНФ', 'Информационные технологии', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ОАиП', 'Основы алгоритмизации и программирования', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ПЗ', 'Представление знаний в компьютерных системах', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ПСП', 'Программирование сетевых приложений', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('МСОИ', 'Моделирование систем обработки информации', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ПИС', 'Проектирование информационных систем', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('КГ', 'Компьютерная геометрия', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ПМАПЛ', 'Полиграф. машины, автоматы и поточные линии', 'ПОиСОИ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('КМС', 'Компьютерные мультимедийные системы', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ОПП', 'Организация полиграф. производства', 'ПОиСОИ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ДМ', 'Дискретная математика', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('МП', 'Математическое программирование', 'ИСиТ') 
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ЛЭВМ', 'Логические основы ЭВМ', 'ИСиТ')                  
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ООП', 'Объектно-ориентированное программирование', 'ИСиТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ЭП', 'Экономика природопользования', 'МиЭП')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ЭТ', 'Экономическая теория', 'ЭТиМ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('БЛЗиПсOO', 'Биология лесных зверей и птиц с осн. охотов.','ОВ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ОСПиЛПХ', 'Основы садово-паркового и лесопаркового хозяйства', 'ЛПиСПС')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ИГ', 'Инженерная геодезия', 'ЛУ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ЛВ', 'Лесоводство', 'ЛЗиДВ') 
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ОХ', 'Органическая химия', 'ОХ')   
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ТРИ', 'Технология резиновых изделий', 'ТНХСиППМ') 
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ВТЛ', 'Водный транспорт леса', 'ТЛ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ТиОЛ', 'Технология и оборудование лесозаготовок', 'ЛМиЛЗ') 
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ТОПИ', 'Технология обогащения полезных ископаемых', 'ТНВиОХТ')
insert into [Subject] (SubjectId, SubjectName, Pulpit) values ('ПЭХ', 'Прикладная электрохимия', 'ХТЭПиМЭЕ')  