insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ИСиТ', 'Информационных систем и технологий', 'ИДиП')
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ПОиСОИ', 'Полиграфического оборудования и систем обработки информации', 'ИДиП')
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('БФ', 'Белорусской филологии', 'ИДиП')
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('РИТ', 'Редакционно-издательских тенологий', 'ИДиП')            
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ПП', 'Полиграфических производств', 'ИДиП')                              
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ЛВ', 'Лесоводства', 'ЛХФ')          
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ОВ', 'Охотоведения', 'ЛХФ')    
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ЛУ', 'Лесоустройства','ЛХФ')           
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ЛЗиДВ', 'Лесозащиты и древесиноведения', 'ЛХФ')                
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ЛКиП', 'Лесных культур и почвоведения', 'ЛХФ') 
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ТиП', 'Туризма и природопользования', 'ЛХФ')              
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ЛПиСПС', 'Ландшафтного проектирования и садово-паркового строительства','ЛХФ')          
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ТЛ', 'Транспорта леса', 'ТТЛП')                          
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ЛМиЛЗ', 'Лесных машин и технологии лесозаготовок', 'ТТЛП')  
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ТДП', 'Технологий деревообрабатывающих производств', 'ТТЛП')   
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ТиДИД', 'Технологии и дизайна изделий из древесины', 'ТТЛП')    
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ОХ', 'Органической химии', 'ТОВ') 
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ТНХСиППМ', 'Технологии нефтехимического синтеза и переработки полимерных материалов', 'ТОВ')
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ХПД', 'Химической переработки древесины', 'ТОВ')             
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ТНВиОХТ', 'Технологии неорганических веществ и общей химической технологии', 'ХТиТ') 
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ХТЭПиМЭЕ', 'Химии, технологии электрохимических производств и материалов электронной техники', 'ХТиТ')  
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('МиАХиСП', 'Машин и аппаратов химических и силикатных производств', 'ХТиТ')               
insert into Pulpit (IdPulpit, PulpitName, Faculty) values ('ПиАХП', 'Процессов и аппаратов химических производств', 'ХТиТ')                                               
insert into Pulpit (IdPulpit, PulpitName, Faculty) values  ('ЭТиМ', 'Экономической теории и маркетинга', 'ИЭФ')   
insert into Pulpit (IdPulpit, PulpitName, Faculty) values  ('МиЭП', 'Менеджмента и экономики природопользования', 'ИЭФ')   
insert into Pulpit (IdPulpit, PulpitName, Faculty) values  ('СБУАиА', 'Статистики, бухгалтерского учета, анализа и аудита', 'ИЭФ')  