insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ИДиП', '1-40 01 02', 'Информационные системы и технологии', 'инженер-программист-системотехник')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ИДиП', '1-47 01 01', 'Издательское дело', 'редактор-технолог')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ИДиП', '1-36 06 01', 'Полиграфическое оборудование и системы обработки информации', 'инженер-электромеханик')                
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ХТиТ', '1-36 01 08', 'Конструирование и производство изделий из композиционных материалов', 'инженер-механик')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ХТиТ', '1-36 07 01', 'Машины и аппараты химических производств и предприятий строительных материалов', 'инженер-механик')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ЛХФ', '1-75 01 01', 'Лесное хозяйство', 'инженер лесного хозяйства')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ЛХФ', '1-75 02 01', 'Садово-парковое строительство', 'инже-нер садово-паркового строительства')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ЛХФ', '1-89 02 02', 'Туризм и природопользование', 'специалист в сфере туризма')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ИЭФ', '1-25 01 07', 'Экономика и управление на предприятии', 'экономист-менеджер')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ИЭФ', '1-25 01 08', 'Бухгалтерский учет, анализ и аудит', 'экономист')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ТТЛП', '1-36 05 01', 'Машины и оборудование лесного комплекса', 'инженер-механик')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ТТЛП', '1-46 01 01', 'Лесоинженерное дело', 'инженер-технолог')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ТОВ', '1-48 01 02', 'Химическая технология органических веществ, материалов и изделий', 'инженер-химик-технолог')           
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ТОВ', '1-48 01 05', 'Химическая технология переработки древесины', 'инженер-химик-технолог')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ТОВ', '1-54 01 03', 'Физико-химические методы и приборы контроля качества продукции', 'инженер по сертификации')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ИТ', '1-40 05 01-03', 'Информационные системы и технологии', 'инженер-программист-системотехник')
insert into Profession (Faculty, IdProfession, ProfessionName, Qualification) values ('ИТ', '1-40 01 01', 'Программное обеспечение информационных технологий', 'инженер-программист') 