insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'СУБД', N'Системы управления базами данных', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'БД', N'Базы данных', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ИНФ', N'Информационные технологии', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ОАиП', N'Основы алгоритмизации и программирования', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ПЗ', N'Представление знаний в компьютерных системах', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ПСП', N'Программирование сетевых приложений', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'МСОИ', N'Моделирование систем обработки информации', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ПИС', N'Проектирование информационных систем', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'КГ', N'Компьютерная геометрия', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ПМАПЛ', N'Полиграф. машины, автоматы и поточные линии', N'ПОиСОИ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'КМС', N'Компьютерные мультимедийные системы', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ОПП', N'Организация полиграф. производства', N'ПОиСОИ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ДМ', N'Дискретная математика', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'МП', N'Математическое программирование', N'ИСиТ') 
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ЛЭВМ', N'Логические основы ЭВМ', N'ИСиТ')                  
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ООП', N'Объектно-ориентированное программирование', N'ИСиТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ЭП', N'Экономика природопользования', N'МиЭП')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ЭТ', N'Экономическая теория', N'ЭТиМ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'БЛЗиПсOO', N'Биология лесных зверей и птиц с осн. охотов.', N'ОВ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ОСПиЛПХ', N'Основы садово-паркового и лесопаркового хозяйства', N'ЛПиСПС')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ИГ', N'Инженерная геодезия', N'ЛУ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ЛВ', N'Лесоводство', N'ЛЗиДВ') 
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ОХ', N'Органическая химия', N'ОХ')   
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ТРИ', N'Технология резиновых изделий', N'ТНХСиППМ') 
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ВТЛ', N'Водный транспорт леса', N'ТЛ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ТиОЛ', N'Технология и оборудование лесозаготовок', N'ЛМиЛЗ') 
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ТОПИ', N'Технология обогащения полезных ископаемых', N'ТНВиОХТ')
insert into [Subject] ([Subject], SubjectName, Pulpit) values (N'ПЭХ', N'Прикладная электрохимия', N'ХТЭПиМЭЕ')    